const { difference } = require("lodash");

const jslt = {
    "quantityPeriodicity": "quantity_period",
    "weightBasis": "weight_basis",
    "toleranceValue": "tolerance_value",
    "tradePriceUom": "price_uom",
    "loadLocationType": "load_location_type",
    "modeOfTransport": "mode_of_transport",
    "tradeId": "trade_id",
    "unloadLocationType": "unload_location_type",
    "periodEndDate": "period_end_date",
    "traderName": "trader_name",
    "totalTradeQty": "total_quantity",
    "dischargeLocation": "unload_location",
    "totalUnits": "total_units",
    "fxrate": "fx_rate",
    "settlementTolerancePercentage": "settlement_tolerance_percentage",
    "tradePriceCurrency": "price_currency",
    "tradeStatus": "trade_overall_status",
    "paymentTerms": "payment_term",
    "profitcenter": "profit_center",
    "tradeDateTime": "trade_date",
    "locationType": "location_type",
    "manualTradeId": "manual_trade_id",
    "provisionalFxRate": "provisional_fx_rate",
    "tradeSettlementCurrency": "settlement_currency",
    "loadLocation": "load_location",
    "quantityUom": "quantity_uom",
    "quantityToleranceType": "quantity_tolerance_type",
    "periodStartDate": "period_start_date",
    "tradeType": "trade_type",
    "priceType": "price_type",
    "tradeTransactionType": "buy_sell",
    "counterpartyCode": "counterparty_code",
    "packageType": "shipment_type",
    "commodity": "commodity",
    "origin": "origin",
    "tradePrice": "price",
    "company": "company",
    "brand": "brand",
    "incoterm": "incoterm",
    "grade": "grade"
  };

  const data = {
    "uuid": "56f3b5e1-db8c-4022-bfdb-d116c8163c3d",
    "created_by": "Harenee",
    "created_timestamp": "2023-09-20 15:17:08.588192",
    "tenant_id": "d7408d31-d720-4173-b76e-0595ce2679b4",
    "updated_by": "Harenee",
    "updated_timestamp": "2023-09-20 15:17:08.588193",
    "brand": "0.0",
    "broker": null,
    "comments": null,
    "commodity": "RBDPL",
    "company": "AAA OILS & FATS PTE LTD",
    "contract_confirmation": null,
    "counterparty": null,
    "delivery_end_date": null,
    "delivery_start_date": null,
    "discharge_location": null,
    "external_package": null,
    "external_package_unit": 0,
    "external_reference": null,
    "factory": null,
    "future_contract_month": null,
    "future_index": null,
    "fxrate": 1,
    "grade": "RBDPL PORAM/STC",
    "incoterm": "FOB",
    "internal_package": null,
    "internal_package_unit": 0,
    "internal_profit_center": null,
    "is_internal_trade": null,
    "is_provisional_pricing": false,
    "load_location": "PASIR GUDANG",
    "location": null,
    "long_contract": null,
    "origin": "Malaysia",
    "package_type": "Bulk",
    "paymentterm": null,
    "percentage": 0,
    "period_end_date": "2024-03-31 00:00:00.000000",
    "period_start_date": "2024-03-01 00:00:00.000000",
    "price_type": "Fixed",
    "profitcenter": "Trading Proprietary\r\n",
    "provisional_fx_rate": 1,
    "provisional_price": 0,
    "provisional_price_currency": null,
    "provisional_price_type": null,
    "provisional_price_uom": null,
    "quantity": 0,
    "quantity_periodicity": "500.0",
    "quantity_tolerance_type": " percentage",
    "quantity_uom": "MT",
    "season": null,
    "special_instructions": null,
    "tolerance_value": "{\"min\":2.00,\"max\":2.00}",
    "total_trade_qty": 500,
    "trade_date_time": "2023-07-03 00:00:00.000000",
    "trade_id": "S/93/23/002587",
    "trade_price": 915,
    "trade_price_currency": "USD",
    "trade_price_uom": "MT",
    "trade_settlement_currency": "USD",
    "trade_transaction_type": 1,
    "trader_name": null,
    "load_location_type": "Port",
    "location_type": "0.0",
    "mode_of_transport": "Ocean",
    "total_units": 0,
    "unload_location_type": "Port",
    "weight_basis": null,
    "delivery_terms_clause": null,
    "payment_terms_clause": null,
    "pricing_terms_clause": null,
    "quantity_terms_clause": null,
    "quotation_period_clause": null,
    "quality_terms_clause": null,
    "commodity_code": "RBDPL",
    "company_code": "AAA",
    "profitcenter_code": null,
    "internal_profitcenter_code": null,
    "counterparty_code": "VITERRA AGRICULTURE SINGAPORE",
    "manual_trade_id": "S/93/23/002587",
    "broker_reference": null,
    "paper_trade": null,
    "settlement_tolerance_percentage": 0,
    "trade_type": "Paper",
    "total_trade_value": null,
    "contract_term": null
  };

  const keys = Object.values(jslt);
//   console.log(keys);

  const dataKeys = Object.keys(data);
//   console.log(dataKeys);

//   console.log(difference(dataKeys,keys));

  const dto = {"tradeId":"Draft/001117","tradeStatus":"Draft","manualTradeId":null,"tradeDateTime":"2023-09-15T00:00:00","tradeTransactionType":"BUY","company":"Transglobal","counterpartyCode":"AGL","profitcenter":"Palm Oil","internalProfitCenter":null,"traderName":"Ishrat","createdBy":"sajith","broker":null,"brokerReference":null,"externalReference":null,"contractTerm":null,"commodity":"CRUDE PALM OIL","origin":"","grade":"","brand":"","season":null,"qualityTermsClause":null,"incoterm":"CPT","locationType":"Country","location":null,"modeOfTransport":"Ocean","loadLocationType":"Port","loadLocation":"NA","unloadLocationType":"Port","dischargeLocation":"NA","packageType":"Bulk","weightBasis":"Net Shipped Weights","quantityUom":"MT","quantity":200,"internalPackage":null,"internalPackageUnit":0,"externalPackage":null,"externalPackageUnit":0,"quantityPeriodicity":"Fixed","periodStartDate":"2023-09-14T00:00:00","periodEndDate":"2023-09-19T00:00:00","deliverySchedule":[{"uuid":"9e2bfff8-38a4-47a7-8c0f-036d3db6cf64","createdBy":"sajith","updatedBy":"sajith","createdTimestamp":"2023-09-20T16:05:17.693895","updatedTimestamp":"2023-09-20T16:05:17.6939","tenantId":"78b8be49-ca51-4195-8531-1f9eadd08171","token":null,"code":null,"tradeId":"Draft/001117","tradeUuid":"f91101d2-c3d6-4528-83fb-045af58be9a0","shipDelMonth":"19 Sep 2023","periodStartDate":"2023-09-14T00:00:00","periodEndDate":"2023-09-19T00:00:00","noOfUnits":1,"quantity":200,"internalpackage":null}],"totalUnits":1,"totalTradeQty":200,"deliveryTermsClause":null,"quantityTermsClause":null,"quantityToleranceType":"percentage","toleranceValue":"{\"min\":2,\"max\":2}","priceType":"Fixed","priceTicker":"","tradePriceCurrency":"USD","tradePrice":250,"tradePriceUom":"MT","totalTradeValue":50000,"quotationPeriodClause":null,"pricingTermsClause":null,"provisionalPricing":false,"provisionalPriceType":"Fixed","percentage":"0","provisionalPrice":"0","provisionalPriceCurrency":null,"provisionalPriceUom":null,"tradeSettlementCurrency":"USD","settlementTolerancePercentage":0,"fxrate":1,"provisionalFxRate":1,"paymentterm":"CAD","paymentTermsClause":"Cash on Delivery","specialInstructions":null,"comments":null,"isInternalTrade":false,"counterparty":"Asia Globe","paperTrade":null,"capacity":null,"deliveryStartDate":null,"deliveryEndDate":null,"futureIndex":null,"tradeType":"Paper","uuid":"f91101d2-c3d6-4528-83fb-045af58be9a0","username":"sajith","updatedBy":"sajith","createdTimestamp":"2023-09-20T16:05:17.690143","updatedTimestamp":"2023-09-20T16:05:17.690165","validFrom":null,"validTo":null,"tenantId":"78b8be49-ca51-4195-8531-1f9eadd08171"};

  console.log(Object.keys(dto).sort());
